language: python
python:
  - "3.4"
install: "pip install -r requirements.txt"
script:
  - python setup.py build
  - python daemon_test.py
notifications:
  notifications:
    email:
      - herron.philip@googlemail.com
branches:
  except:
    - gh-pages
