language: java
jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8
 os:
   - linux
   - osx
script: ./gradlew build
notifications:
  notifications:
    email:
      - herron.philip@googlemail.com
branches:
  except:
    - gh-pages