language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install build-essential autoconf libtool automake libevent-dev
install: "pip install -r requirements.txt"
script: ./travis-build.sh
branches:
  only:
    - master
notifications:
  recipients:
    - redbrain@gcc.gnu.org
  email:
    on_success: change
    on_failure: always
